/** Theme-aware Tailwind class bundles for Discover & Request UI. */
export const discoveryTheme = {
    heading: 'text-2xl font-black text-text tracking-tight',
    subheading: 'text-sm text-muted mt-1',
    sectionTitle: 'text-xl font-bold text-text',
    tabBar: 'w-full flex flex-wrap items-center gap-1 p-1 rounded-xl bg-white/[0.04] border border-border/80 backdrop-blur-md',
    tab: 'flex items-center gap-2 px-3.5 py-2 rounded-lg text-sm font-bold transition-all whitespace-nowrap text-muted hover:text-text hover:bg-white/5',
    tabActive: 'bg-plex/20 text-plex ring-1 ring-inset ring-plex/50 shadow-none hover:bg-plex/25 hover:text-plex',
    tabSticky: 'sticky top-0 z-30 -mx-1 px-1 py-2 bg-background/85 backdrop-blur-md',
    toolbarBtn: 'flex items-center gap-2 px-4 py-2 bg-white/5 border border-border hover:bg-white/10 rounded-lg text-text/80 hover:text-text font-bold transition-colors',
    mobileNavBtn: 'w-full flex items-center justify-between p-3 rounded-lg bg-white/5 border border-border text-text font-bold',
    mobileNavMenu: 'absolute top-full left-0 right-0 mt-2 bg-card border border-border rounded-lg overflow-hidden z-50',
    mobileNavItem: 'w-full flex items-center gap-2 p-3 text-left hover:bg-white/5 text-muted',
    mobileNavItemActive: 'text-text bg-white/5',
    filterChip: 'inline-flex items-center gap-2 px-3 py-2 rounded-xl text-sm font-bold border transition-colors bg-white/[0.03] border-border text-muted hover:text-text hover:border-border',
    filterChipActive: 'bg-plex/15 border-plex/40 text-text',
    filterChipCount: 'text-[11px] px-1.5 py-0.5 rounded-full bg-white/5 text-muted',
    filterChipCountActive: 'bg-plex/20 text-plex',
    emptyState: 'rounded-xl border border-border bg-white/[0.03] px-6 py-12 text-center',
    emptyTitle: 'text-text/80 font-semibold',
    emptyBody: 'text-sm text-muted mt-2',
    searchInput: 'w-full bg-background/90 border-2 border-border/80 focus:border-plex focus:bg-background rounded-xl py-2.5 sm:py-3 pl-11 sm:pl-12 pr-11 text-sm sm:text-base text-text font-medium outline-none transition-all placeholder:text-muted/55',
    searchDropdown: 'max-h-[min(420px,50vh)] overflow-y-auto custom-scrollbar rounded-xl border border-border bg-card',
    searchResultBtn: 'w-full flex items-center gap-4 p-3 hover:bg-white/[0.06] border-b border-border last:border-0 text-left transition-colors bg-card',
    heroShell: 'relative w-full rounded-2xl border border-border min-h-[220px] sm:min-h-[280px] overflow-visible',
    heroBackdrop: 'absolute inset-0 rounded-2xl overflow-hidden bg-gradient-to-br from-plex/20 to-background/80',
    heroTitle: 'text-2xl sm:text-4xl font-bold text-text tracking-tight',
    heroChip: 'inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-[11px] sm:text-xs font-bold border border-border/80 bg-background/85 text-text backdrop-blur-md hover:bg-plex hover:text-background hover:border-plex transition-colors',
    personalPanel: 'rounded-2xl border border-plex/25 bg-gradient-to-br from-plex/[0.12] via-card/50 to-transparent p-4 sm:p-5 flex flex-col gap-5',
    personalEyebrow: 'text-[10px] uppercase tracking-[0.25em] font-black text-plex',
    browseSection: 'flex flex-col gap-4 pt-2',
    drawerOverlay: 'fixed inset-0 bg-background/80 backdrop-blur-sm z-[100] transition-opacity duration-300',
    drawerPanel: 'fixed top-0 right-0 h-full w-full max-w-[440px] bg-card border-l border-border z-[101] flex flex-col transition-transform duration-500 ease-[cubic-bezier(0.32,0.72,0,1)]',
    drawerHeader: 'flex items-center justify-between p-6 border-b border-border bg-background/20',
    drawerTitle: 'text-2xl font-black text-text tracking-tight flex items-center gap-3',
    posterEmpty: 'flex flex-col items-center justify-center py-16 px-6 rounded-2xl border border-dashed border-border bg-white/[0.02] text-center',
};
