import { createAnalyticsCacheScheduler } from './analytics-cache-scheduler.js';
import { registerJellystatAnalyticsRoutes } from './analytics-jellystat.js';
import { registerPlexAnalyticsRoutes } from './analytics-plex-routes.js';
import { createTautulliAnalytics } from './analytics-tautulli.js';

export const createAnalyticsService = ({
    app,
    requireAuth,
    requireMember,
    requireAdmin,
    configPath,
    usersPath,
    analyticsCachePath,
    personalAnalyticsCachePath,
    trendingCachePath,
    plexStatsCachePath,
    loadFile,
    saveFile,
    getPlexConnectionUri,
    resolveIntegrationUrlForFetch,
    fetchWithTimeout,
    fetchPlexServerAccounts,
    resolveLocalPlexAccountId,
    resolveCurrentAdmin,
    plexImageUrl,
    withBasePath,
    jellyfinItemUrl,
    isJellyfinConfigured,
    buildPlexStatsCache,
    getCachedPlexMetadata,
    setCachedPlexMetadata,
    enrichRecentItemsWithMediaTags,
    sendEmail,
    escapeHtmlAttr,
    markTaskStart,
    markTaskEnd,
    systemJobs,
    runHeavyJob,
    log,
}) => {
    const tautulli = createTautulliAnalytics({
        app,
        requireAuth,
        requireMember,
        configPath,
        loadFile,
        resolveIntegrationUrlForFetch,
        log,
    });

    registerJellystatAnalyticsRoutes({
        app,
        requireAuth,
        requireMember,
        configPath,
        loadFile,
        resolveIntegrationUrlForFetch,
        fetchWithTimeout,
        withBasePath,
        jellyfinItemUrl,
        isJellyfinConfigured,
        log,
    });

    const personalAnalyticsCache = registerPlexAnalyticsRoutes({
        app,
        requireAuth,
        requireMember,
        requireAdmin,
        configPath,
        usersPath,
        analyticsCachePath,
        personalAnalyticsCachePath,
        trendingCachePath,
        plexStatsCachePath,
        loadFile,
        saveFile,
        getPlexConnectionUri,
        resolveIntegrationUrlForFetch,
        fetchPlexServerAccounts,
        resolveLocalPlexAccountId,
        resolveCurrentAdmin,
        plexImageUrl,
        getCachedPlexMetadata,
        setCachedPlexMetadata,
        buildPlexStatsCache,
        sendEmail,
        escapeHtmlAttr,
        tautulli,
        log,
    });

    return {
        ...createAnalyticsCacheScheduler({
            app,
            requireAuth,
            requireMember,
            configPath,
            usersPath,
            analyticsCachePath,
            trendingCachePath,
            loadFile,
            saveFile,
            getPlexConnectionUri,
            plexImageUrl,
            enrichRecentItemsWithMediaTags,
            markTaskStart,
            markTaskEnd,
            systemJobs,
            runHeavyJob,
            log,
        }),
        ...personalAnalyticsCache,
    };
};
