import { registerAuthRoutes } from '../auth/auth-routes.js';
import { registerInviteRoutes } from '../users/invite-routes.js';
import { registerAdminRoutes } from '../admin/admin-routes.js';
import { registerConfigRoutes } from '../config/config-routes.js';
import { registerPublicStatusRoutes } from '../status/public-status-routes.js';
import { registerPlexRoutes } from '../plex/plex-routes.js';
import { registerJellyfinRoutes } from '../jellyfin/jellyfin-routes.js';
import { registerMediaStackRoutes } from '../media-stack/media-stack-routes.js';
import { registerRequestAppRoutes } from '../request-app/request-app-routes.js';
import { registerMediaIssueRoutes } from '../media-stack/media-issue-routes.js';
import { registerStaticShellRoutes } from '../http/static-shell-routes.js';
import { registerCommunicationRoutes } from '../comms/communication-routes.js';
import { registerKillRuleRoutes } from '../admin/kill-rule-routes.js';

export const registerPortalRoutes = ({
    app,
    appVersion,
    basePath,
    stripBasePathFromUrl,
    clearSessionCookie,
    setSessionCookie,
    withBasePath,
    services,
}) => {
    const {
        env: {
            PORT,
            PUBLIC_BASE_URL,
            JWT_SECRET,
            SECRET_MASK,
            SETUP_TOKEN,
        },
        paths: {
            CONFIG_PATH,
            INVITES_PATH,
            USERS_PATH,
            DELETED_USERS_PATH,
            AUDIT_LOG_PATH,
            ANALYTICS_CACHE_PATH,
            TRENDING_CACHE_PATH,
            PLEX_STATS_CACHE_PATH,
            KILL_RULES_PATH,
            MEDIA_ISSUES_PATH,
            CONFIG_DIR,
        },
        authRateLimit,
        authCallbackRateLimit,
        jellyfinQuickConnectPollRateLimit,
        publicReadRateLimit,
        setupRateLimit,
        canRunInitialSetup,
        sanitizeIntegrationUrl,
        loadFile,
        saveFile,
        appendAuditLog,
        rememberDeletedUser,
        statusRuntime,
        sendEmail,
        sendAdjustmentEmail,
        checkAndSendNotifications,
        memberNotifications,
        startBroadcast,
        sendTestBroadcast,
        sendTestNewsletter,
        sendManualNewsletter,
        checkAndSendNewsletter,
        apiFetch,
        jellyfinHeaders,
        jellyfinItemUrl,
        fetchWithTimeout,
        normalizePlexToken,
        resolveConfiguredPlexServerUrl,
        fetchOwnedPlexServers,
        validatePlexServerAdminToken,
        verifyInitialSetupPlexOwner,
        fetchPlexServerAccounts,
        resolveLocalPlexAccountId,
        getPlexConnectionUri,
        invalidatePlexConnectionCaches,
        syncAdminPlexIdFromConfigToken,
        getAdminId,
        resolveCurrentAdmin,
        requireAuth,
        requireAdmin,
        requireMember,
        getSessionUser,
        plexSessionsSnapshot,
        membershipSync,
        syncUsers,
        syncJellyfinUsers,
        revokePlexAccess,
        inviteUserToPlex,
        checkAndRevoke,
        getAdminProfile,
        invalidateAdminProfileCache,
        plexStatsService,
        loadPlexStatsFromDisk,
        buildPlexStatsCache,
        plexImageService,
        plexDashboardService,
        applyBackupPayload,
        createBackupObject,
        enforceBackupRetention,
        listBackupFiles,
        writeBackupToFolder,
        BACKUP_DIR,
        calculateAnalyticsStats,
        calculateTrendingStats,
        checkAndCleanupInactive,
        runAutoBackupCycle,
        startBackgroundService,
        withCache,
        normalizeExternalBaseUrl,
        computeNextBackupRun,
        getTasksSnapshot,
        findRunnableTask,
        markTaskStart,
        markTaskEnd,
        systemJobs,
        wireRequestAppServices,
        DEFAULT_DASHBOARD_LAYOUT,
        normalizeSectionLayout,
        isJellyfinConfigured,
        isPortalConfigured,
        getClientId,
        resolveIntegrationUrlForFetch,
        findLocalUserForSession,
        escapeHtmlAttr,
        log,
    } = services;

    registerAuthRoutes({
        app,
        authRateLimit,
        authCallbackRateLimit,
        jellyfinQuickConnectPollRateLimit,
        publicReadRateLimit,
        setupRateLimit,
        requireAuth,
        requireMember,
        requireAdmin,
        appVersion,
        configPath: CONFIG_PATH,
        usersPath: USERS_PATH,
        deletedUsersPath: DELETED_USERS_PATH,
        jwtSecret: JWT_SECRET,
        forceSecureCookies: services.env.FORCE_SECURE_COOKIES,
        loadFile,
        saveFile,
        apiFetch,
        jellyfinHeaders,
        isJellyfinConfigured,
        isPortalConfigured,
        resolveIntegrationUrlForFetch,
        getClientId,
        withBasePath,
        clearSessionCookie,
        setSessionCookie,
        appendAuditLog,
        findLocalUserForSession,
        syncAdminPlexIdFromConfigToken,
        getAdminId,
        resolveCurrentAdmin,
        resolveConfiguredPlexServerUrl,
        fetchOwnedPlexServers,
        canRunInitialSetup,
        inviteUserToPlex,
        getPlexConnectionUri,
        resolveLocalPlexAccountId,
        fetchPlexServerAccounts,
        getAdminProfile,
        membershipSync,
        fetchImpl: fetchWithTimeout,
        log,
    });

    registerConfigRoutes({
        app,
        requireAdmin,
        setupRateLimit,
        publicReadRateLimit,
        configPath: CONFIG_PATH,
        secretMask: SECRET_MASK,
        setupToken: SETUP_TOKEN,
        jwtSecret: JWT_SECRET,
        basePath,
        appVersion,
        defaultDashboardLayout: DEFAULT_DASHBOARD_LAYOUT,
        loadFile,
        saveFile,
        isPortalConfigured,
        isJellyfinConfigured,
        normalizePlexToken,
        resolveConfiguredPlexServerUrl,
        verifyInitialSetupPlexOwner,
        resolveCurrentAdmin,
        canRunInitialSetup,
        sanitizeIntegrationUrl,
        fetchOwnedPlexServers,
        validatePlexServerAdminToken,
        syncAdminPlexIdFromConfigToken,
        invalidatePlexConnectionCaches,
        invalidateAdminProfileCache,
        reconcileStatusConfig: () => statusRuntime.reconcileStatusConfig(),
        computeNextBackupRun,
        systemJobs,
        startBackgroundService: () => startBackgroundService(),
        normalizeSectionLayout,
        sendEmail,
        resolveIntegrationUrlForFetch,
        fetchWithTimeout,
        getPlexConnectionUri,
        log,
    });

    registerPlexRoutes({
        app,
        requireAuth,
        requireMember,
        requireAdmin,
        configPath: CONFIG_PATH,
        loadFile,
        getPlexConnectionUri,
        fetch,
        fetchWithTimeout,
        plexSessionsSnapshot,
        plexImageService,
        plexDashboardService,
        plexStatsService,
        loadPlexStatsFromDisk,
        buildPlexStatsCache,
        withBasePath,
        log,
    });

    registerCommunicationRoutes({
        app,
        requireAdmin,
        configPath: CONFIG_PATH,
        usersPath: USERS_PATH,
        loadFile,
        saveFile,
        startBroadcast,
        sendTestBroadcast,
        sendTestNewsletter,
        sendManualNewsletter,
        sendEmail,
        escapeHtmlAttr,
        log,
    });

    registerInviteRoutes({
        app,
        requireAdmin,
        authRateLimit,
        publicReadRateLimit,
        setupRateLimit,
        configPath: CONFIG_PATH,
        usersPath: USERS_PATH,
        invitesPath: INVITES_PATH,
        jwtSecret: JWT_SECRET,
        secretMask: SECRET_MASK,
        loadFile,
        saveFile,
        normalizePlexToken,
        isPortalConfigured,
        resolveCurrentAdmin,
        fetchOwnedPlexServers,
        validatePlexServerAdminToken,
        canRunInitialSetup,
        resolveConfiguredPlexServerUrl,
        resolveIntegrationUrlForFetch,
        fetchWithTimeout,
        syncUsers,
        syncJellyfinUsers,
        appendAuditLog,
        sendEmail,
        getAdminProfile,
        getClientId,
        inviteUserToPlex,
        getAdminId,
        setSessionCookie,
        membershipSync,
        log,
    });

    registerAdminRoutes({
        app,
        requireAdmin,
        requireAuth,
        requireMember,
        jwtSecret: JWT_SECRET,
        configDir: CONFIG_DIR,
        configPath: CONFIG_PATH,
        usersPath: USERS_PATH,
        deletedUsersPath: DELETED_USERS_PATH,
        auditLogPath: AUDIT_LOG_PATH,
        analyticsCachePath: ANALYTICS_CACHE_PATH,
        trendingCachePath: TRENDING_CACHE_PATH,
        plexStatsCachePath: PLEX_STATS_CACHE_PATH,
        appVersion,
        loadFile,
        saveFile,
        getTasksSnapshot,
        findRunnableTask,
        markTaskStart,
        markTaskEnd,
        syncUsers,
        checkAndSendNotifications,
        checkAndRevoke,
        checkAndSendNewsletter,
        checkAndCleanupInactive: (...args) => checkAndCleanupInactive(...args),
        calculateAnalyticsStats: (...args) => calculateAnalyticsStats(...args),
        calculateTrendingStats: (...args) => calculateTrendingStats(...args),
        buildPlexStatsCache,
        runAutoBackupCycle: (...args) => runAutoBackupCycle(...args),
        applyBackupPayload,
        createBackupObject,
        enforceBackupRetention,
        listBackupFiles,
        writeBackupToFolder,
        backupDir: BACKUP_DIR,
        appendAuditLog,
        sendAdjustmentEmail,
        inviteUserToPlex,
        revokePlexAccess,
        rememberDeletedUser,
        resolveCurrentAdmin,
        clearSessionCookie,
        setSessionCookie,
        membershipSync,
        log,
    });

    registerPublicStatusRoutes({
        app,
        publicReadRateLimit,
        requireAuth,
        requireAdmin,
        configPath: CONFIG_PATH,
        loadFile,
        statusRuntime,
        getSessionUser,
        getAdminProfile,
        isPortalConfigured,
        getCachedPlexStats: () => plexStatsService.getCachedPlexStats(),
        loadPlexStatsFromDisk,
    });

    registerJellyfinRoutes({
        app,
        requireAuth,
        requireMember,
        publicReadRateLimit,
        configPath: CONFIG_PATH,
        loadFile,
        isJellyfinConfigured,
        resolveIntegrationUrlForFetch,
        fetchWithTimeout,
        withCache,
        jellyfinHeaders,
        withBasePath,
        jellyfinItemUrl,
        log,
    });

    registerStaticShellRoutes({
        app,
        basePath,
        publicBaseUrl: PUBLIC_BASE_URL,
        port: PORT,
        configPath: CONFIG_PATH,
        loadFile,
        getAdminProfile,
        stripBasePathFromUrl,
        log,
    });

    const mediaStackRoutes = registerMediaStackRoutes({
        app,
        requireAuth,
        requireMember,
        configPath: CONFIG_PATH,
        loadFile,
        withCache,
        fetch,
        normalizeExternalBaseUrl,
    });

    wireRequestAppServices(mediaStackRoutes);

    registerRequestAppRoutes({
        app,
        requireAuth,
        requireMember,
        requireAdmin,
        configPath: CONFIG_PATH,
        loadFile,
        requestAppService: services.requestAppService,
        appendAuditLog,
        notifyRequestUpdate: memberNotifications.notifyRequestUpdate,
        log,
    });

    registerMediaIssueRoutes({
        app,
        requireAuth,
        requireMember,
        requireAdmin,
        configPath: CONFIG_PATH,
        issuePath: MEDIA_ISSUES_PATH,
        loadFile,
        saveFile,
        requestAppService: services.requestAppService,
        fetch,
        resolveIntegrationUrlForFetch,
        getPlexConnectionUri,
        appendAuditLog,
        notifyIssueReply: memberNotifications.notifyIssueReply,
        log,
    });

    registerKillRuleRoutes({
        app,
        requireAdmin,
        killRulesPath: KILL_RULES_PATH,
        loadFile,
        saveFile,
    });

    return mediaStackRoutes;
};
