import type { DashboardLayoutConfig } from '../shared/dashboardLayout';
import type { ArrInstance, PlexServer } from '../shared/types';
import type { ScannerSettings } from './ScannerSettingsPanel';

export type SettingsFormValues = {
    token: string;
    mediaServerType: 'plex' | 'jellyfin';
    plexServerUrl: string;
    jellyfinUrl: string;
    jellyfinApiKey: string;
    servers: PlexServer[];
    selectedServer: string;
    checkInterval: number;
    hideStreamUsers: string;
    useTrendingSlideshowOnLogin: boolean;
    showLoginServerStats: boolean;
    publicStatusEnabled: boolean;
    defaultLibraryIds: string[];
    smtpHost: string;
    smtpPort: number;
    smtpUser: string;
    smtpPass: string;
    smtpFrom: string;
    smtpSecure: boolean;
    emailDaysBefore: number;
    testRecipient: string;
    newsletterFrequency: string;
    newsletterDay: number;
    publicDomain: string;
    contactUrl: string;
    contactEmail: string;
    discordEnabled: boolean;
    discordInviteUrl: string;
    discordChatChannelLabel: string;
    discordMediaChannelLabel: string;
    discordGuildId: string;
    discordBotToken: string;
    discordBotEnabled: boolean;
    discordWebhookUrl: string;
    discordNotifyRequestUpdates: boolean;
    discordNotifyIssueReplies: boolean;
    discordNotifyWatchlistAvailable: boolean;
    discordLlmEnabled: boolean;
    discordLlmUrl: string;
    discordLlmApiKey: string;
    discordLlmModel: string;
    discordAgentEnabled: boolean;
    discordSearxngUrl: string;
    discordBraveSearchApiKey: string;
    discordTavilyApiKey: string;
    discordMentionNl: boolean;
    inactiveCleanupEnabled: boolean;
    inactiveCleanupDays: number;
    arrInstances: ArrInstance[];
    tautulliUrl: string;
    tautulliApiKey: string;
    jellystatUrl: string;
    jellystatApiKey: string;
    dashboardLayout: DashboardLayoutConfig;
    customLogoUrl: string;
    backgroundImageUrl: string;
    useScrollRevealAnimations: boolean;
    useCinematicLoading: boolean;
    useBrandedSkeleton: boolean;
    useTrendingSlideshow: boolean;
    trendingSlideshowInterval: number;
    tmdbApiKey: string;
    tvdbApiKey: string;
    tvdbPin: string;
    cacheRefreshMinutes: number;
    brandingTheme: string;
    referralEnabled: boolean;
    referralTrialDays: number;
    referralRewardDays: number;
    announcement: string;
    use24HourClock: boolean;
    showPosterQualityBadges: boolean;
    allowTemporaryAccess: boolean;
    navOrder: string[];
    navHiddenKeys: string[];
    scannerEnabled: boolean;
    scannerHomeWidgetEnabled: boolean;
    scannerWebhooksVisible: boolean;
    scannerManualPathVisible: boolean;
    scanner: ScannerSettings;
    upgraderEnabled: boolean;
    upgraderAutomationEnabled: boolean;
    upgraderHuntMissingEpisodes: boolean;
    upgraderHuntAvailableMovies: boolean;
    upgraderMinSizeGB: number;
    upgraderMaxActionsPerHour: number;
    upgraderMaxDownloadsPerLibrary: number;
    upgraderMinScoreDelta: number;
    upgraderPreferences: {
        preferDolbyVisionHdr: boolean;
        preferAtmos: boolean;
        preferRemux: boolean;
        preferSeasonPacks: boolean;
    };
    qcCleanupAutomationEnabled: boolean;
    qcIntegrityEnabled: boolean;
    qcIntegrityAutomationEnabled: boolean;
    qcIntegrityRequireAudio: boolean;
    qcIntegrityPathMaps: Array<{ from: string; to: string }>;
    qcIntegrityMaxPerCycle: number;
    qcIntegrityDecodeWindowSec: number;
    qcIntegrityDecodeTimeoutMs: number;
    qcMetaDlMinutes: number;
    qcStalledHours: number;
    qcCompletedNotImportingMinutes: number;
    qcOrphanGraceMinutes: number;
    qcMaxStrikes: number;
    qcResearchThrottleHours: number;
    qcSnoozeDefaultHours: number;
    qcDiscordDigestEnabled: boolean;
    qcPreferImportDiscordOnly: boolean;
    qcQbitUrl: string;
    qcQbitUsername: string;
    qcQbitPassword: string;
    qcSabUrl: string;
    qcSabApiKey: string;
    qcBlockedExtensions: string[];
    logoFile: File | null;
};

export type SaveAdminValues = {
    customLogoUrl: string;
    autoBackupEnabled: boolean;
    autoBackupIntervalDays: number;
    autoBackupRetentionCount: number;
};
