import type React from 'react';

import { normalizeSectionLayout, type DashboardLayoutConfig } from '../shared/dashboardLayout';
import { normalizeNavHiddenKeys, normalizeSettingsNavOrder } from './settingsNavOrder';
import type { ArrInstance } from '../shared/types';
import type { ScannerSettings } from './ScannerSettingsPanel';

type SettingsHydrationSetters = {
    setToken: (value: string) => void;
    setMediaServerType: (value: 'plex' | 'jellyfin') => void;
    setPlexServerUrl: (value: string) => void;
    setJellyfinUrl: (value: string) => void;
    setJellyfinApiKey: (value: string) => void;
    setSelectedServer: (value: string) => void;
    setCheckInterval: (value: number) => void;
    setSmtpHost: (value: string) => void;
    setSmtpPort: (value: number) => void;
    setSmtpUser: (value: string) => void;
    setSmtpPass: (value: string) => void;
    setSmtpFrom: (value: string) => void;
    setSmtpSecure: (value: boolean) => void;
    setEmailDaysBefore: (value: number) => void;
    setNewsletterFrequency: (value: string) => void;
    setNewsletterDay: (value: number) => void;
    setInactiveCleanupEnabled: (value: boolean) => void;
    setInactiveCleanupDays: (value: number) => void;
    setPublicDomain: (value: string) => void;
    setContactUrl: (value: string) => void;
    setContactEmail: (value: string) => void;
    setDiscordEnabled: (value: boolean) => void;
    setDiscordInviteUrl: (value: string) => void;
    setDiscordChatChannelLabel: (value: string) => void;
    setDiscordMediaChannelLabel: (value: string) => void;
    setDiscordGuildId: (value: string) => void;
    setDiscordBotToken: (value: string) => void;
    setDiscordBotEnabled: (value: boolean) => void;
    setDiscordWebhookUrl: (value: string) => void;
    setDiscordNotifyRequestUpdates: (value: boolean) => void;
    setDiscordNotifyIssueReplies: (value: boolean) => void;
    setDiscordNotifyWatchlistAvailable: (value: boolean) => void;
    setDiscordLlmEnabled: (value: boolean) => void;
    setDiscordLlmUrl: (value: string) => void;
    setDiscordLlmApiKey: (value: string) => void;
    setDiscordLlmModel: (value: string) => void;
    setDiscordAgentEnabled: (value: boolean) => void;
    setDiscordSearxngUrl: (value: string) => void;
    setDiscordBraveSearchApiKey: (value: string) => void;
    setDiscordTavilyApiKey: (value: string) => void;
    setDiscordMentionNl: (value: boolean) => void;
    setArrInstances: (value: ArrInstance[]) => void;
    setTautulliUrl: (value: string) => void;
    setTautulliApiKey: (value: string) => void;
    setJellystatUrl: (value: string) => void;
    setJellystatApiKey: (value: string) => void;
    setBrandingTheme: (value: string) => void;
    setCustomLogoUrl: (value: string) => void;
    setBackgroundImageUrl: (value: string) => void;
    setUseScrollRevealAnimations: (value: boolean) => void;
    setUseCinematicLoading: (value: boolean) => void;
    setUseBrandedSkeleton: (value: boolean) => void;
    setUseTrendingSlideshow: (value: boolean) => void;
    setTrendingSlideshowInterval: (value: number) => void;
    setTmdbApiKey: (value: string) => void;
    setTvdbApiKey: (value: string) => void;
    setTvdbPin: (value: string) => void;
    setCacheRefreshMinutes: (value: number) => void;
    setReferralEnabled: (value: boolean) => void;
    setReferralTrialDays: (value: number) => void;
    setReferralRewardDays: (value: number) => void;
    setAnnouncement: (value: string) => void;
    setNavOrder: (value: string[]) => void;
    setNavHiddenKeys: (value: string[]) => void;
    setHideStreamUsers: (value: string) => void;
    setUseTrendingSlideshowOnLogin: (value: boolean) => void;
    setShowLoginServerStats: (value: boolean) => void;
    setPublicStatusEnabled: (value: boolean) => void;
    setDefaultLibraryIds: (value: string[]) => void;
    setUse24HourClock: (value: boolean) => void;
    setShowPosterQualityBadges: (value: boolean) => void;
    setAllowTemporaryAccess: (value: boolean) => void;
    setAutoBackupEnabled: (value: boolean) => void;
    setAutoBackupIntervalDays: (value: number) => void;
    setAutoBackupRetentionCount: (value: number) => void;
    setDashboardLayout: (value: DashboardLayoutConfig) => void;
    setScannerEnabled: (value: boolean) => void;
    setScannerHomeWidgetEnabled: (value: boolean) => void;
    setScannerWebhooksVisible: (value: boolean) => void;
    setScannerManualPathVisible: (value: boolean) => void;
    setScanner: (value: ScannerSettings) => void;
    setUpgraderEnabled: (value: boolean) => void;
    setUpgraderAutomationEnabled: (value: boolean) => void;
    setUpgraderHuntMissingEpisodes: (value: boolean) => void;
    setUpgraderHuntAvailableMovies: (value: boolean) => void;
    setUpgraderMinSizeGB: (value: number) => void;
    setUpgraderMaxActionsPerHour: (value: number) => void;
    setUpgraderMinScoreDelta: (value: number) => void;
    setUpgraderPreferences: (value: {
        preferDolbyVisionHdr: boolean;
        preferAtmos: boolean;
        preferRemux: boolean;
        preferSeasonPacks: boolean;
    }) => void;
    setQcCleanupAutomationEnabled: (value: boolean) => void;
    setQcMetaDlMinutes: (value: number) => void;
    setQcStalledHours: (value: number) => void;
    setQcCompletedNotImportingMinutes: (value: number) => void;
    setQcResearchThrottleHours: (value: number) => void;
    setQcSnoozeDefaultHours: (value: number) => void;
    setQcDiscordDigestEnabled: (value: boolean) => void;
    setQcPreferImportDiscordOnly: (value: boolean) => void;
    setQcQbitUrl: (value: string) => void;
    setQcQbitUsername: (value: string) => void;
    setQcQbitPassword: (value: string) => void;
    setQcSabUrl: (value: string) => void;
    setQcSabApiKey: (value: string) => void;
    setQcBlockedExtensions: (value: string[]) => void;
    setTestRecipient: (value: string) => void;
    setServers: (value: any[]) => void;
    dashboardLayoutRef: React.MutableRefObject<DashboardLayoutConfig>;
};

export const hydrateSettingsFromConfig = (initialSettings: any, setters: SettingsHydrationSetters) => {
    setters.setToken(initialSettings.token || '');
    setters.setMediaServerType(initialSettings.mediaServerType === 'jellyfin' ? 'jellyfin' : 'plex');
    setters.setPlexServerUrl(initialSettings.plexServerUrl || '');
    setters.setJellyfinUrl(initialSettings.jellyfinUrl || '');
    setters.setJellyfinApiKey(initialSettings.jellyfinApiKey || '');
    setters.setSelectedServer(initialSettings.serverIdentifier || '');
    setters.setCheckInterval(initialSettings.checkIntervalMinutes || 60);
    setters.setSmtpHost(initialSettings.smtpHost || '');
    setters.setSmtpPort(initialSettings.smtpPort || 587);
    setters.setSmtpUser(initialSettings.smtpUser || '');
    setters.setSmtpPass(initialSettings.smtpPass || '');
    setters.setSmtpFrom(initialSettings.smtpFrom || '');
    setters.setSmtpSecure(!!initialSettings.smtpSecure);
    setters.setEmailDaysBefore(initialSettings.emailDaysBefore || 7);
    setters.setNewsletterFrequency(initialSettings.newsletterFrequency || 'disabled');
    setters.setNewsletterDay(initialSettings.newsletterDay || 0);
    setters.setInactiveCleanupEnabled(!!initialSettings.inactiveCleanupEnabled);
    setters.setInactiveCleanupDays(initialSettings.inactiveCleanupDays || 90);
    setters.setPublicDomain(initialSettings.publicDomain || 'https://portal.yourdomain.com');
    setters.setContactUrl(initialSettings.contactUrl || '');
    setters.setContactEmail(initialSettings.contactEmail || '');
    setters.setDiscordEnabled(!!initialSettings.discordEnabled);
    setters.setDiscordInviteUrl(initialSettings.discordInviteUrl || '');
    setters.setDiscordChatChannelLabel(initialSettings.discordChatChannelLabel || '');
    setters.setDiscordMediaChannelLabel(initialSettings.discordMediaChannelLabel || '');
    setters.setDiscordGuildId(initialSettings.discordGuildId || '');
    setters.setDiscordBotToken(initialSettings.discordBotToken || '');
    setters.setDiscordBotEnabled(!!initialSettings.discordBotEnabled);
    setters.setDiscordWebhookUrl(initialSettings.discordWebhookUrl || '');
    setters.setDiscordNotifyRequestUpdates(initialSettings.discordNotifyRequestUpdates !== false);
    setters.setDiscordNotifyIssueReplies(initialSettings.discordNotifyIssueReplies !== false);
    setters.setDiscordNotifyWatchlistAvailable(initialSettings.discordNotifyWatchlistAvailable !== false);
    setters.setDiscordLlmEnabled(!!initialSettings.discordLlmEnabled);
    setters.setDiscordLlmUrl(initialSettings.discordLlmUrl || '');
    setters.setDiscordLlmApiKey(initialSettings.discordLlmApiKey || '');
    setters.setDiscordLlmModel(initialSettings.discordLlmModel || 'gpt-4o-mini');
    setters.setDiscordAgentEnabled(initialSettings.discordAgentEnabled !== false);
    setters.setDiscordSearxngUrl(initialSettings.discordSearxngUrl || '');
    setters.setDiscordBraveSearchApiKey(initialSettings.discordBraveSearchApiKey || '');
    setters.setDiscordTavilyApiKey(initialSettings.discordTavilyApiKey || '');
    setters.setDiscordMentionNl(!!initialSettings.discordMentionNl);
    setters.setArrInstances(Array.isArray(initialSettings.arrInstances) ? initialSettings.arrInstances : []);
    setters.setTautulliUrl(initialSettings.tautulliUrl || '');
    setters.setTautulliApiKey(initialSettings.tautulliApiKey || '');
    setters.setJellystatUrl(initialSettings.jellystatUrl || '');
    setters.setJellystatApiKey(initialSettings.jellystatApiKey || '');
    setters.setBrandingTheme(initialSettings.brandingTheme || 'plex');
    setters.setCustomLogoUrl(initialSettings.customLogoUrl || '');
    setters.setBackgroundImageUrl(initialSettings.backgroundImageUrl || '');
    setters.setUseScrollRevealAnimations(!!initialSettings.useScrollRevealAnimations);
    setters.setUseCinematicLoading(!!initialSettings.useCinematicLoading);
    setters.setUseBrandedSkeleton(initialSettings.useBrandedSkeleton !== false);
    setters.setUseTrendingSlideshow(!!initialSettings.useTrendingSlideshow);
    setters.setTrendingSlideshowInterval(initialSettings.trendingSlideshowInterval || 30);
    setters.setTmdbApiKey(initialSettings.tmdbApiKey || '');
    setters.setTvdbApiKey(initialSettings.tvdbApiKey || '');
    setters.setTvdbPin(initialSettings.tvdbPin || '');
    setters.setCacheRefreshMinutes(Number(initialSettings.cacheRefreshMinutes) || 5);
    setters.setReferralEnabled(!!initialSettings.referralEnabled);
    setters.setReferralTrialDays(initialSettings.referralTrialDays || 3);
    setters.setReferralRewardDays(initialSettings.referralRewardDays || 7);
    setters.setAnnouncement(initialSettings.announcement || '');
    if (initialSettings.navOrder) setters.setNavOrder(normalizeSettingsNavOrder(initialSettings.navOrder));
    setters.setNavHiddenKeys(normalizeNavHiddenKeys(initialSettings.navHiddenKeys));
    setters.setHideStreamUsers(initialSettings.hideStreamUsers === 'hidden' ? 'hidden' : 'anonymous');
    setters.setUseTrendingSlideshowOnLogin(initialSettings.useTrendingSlideshowOnLogin !== false);
    setters.setShowLoginServerStats(initialSettings.showLoginServerStats === true);
    setters.setPublicStatusEnabled(initialSettings.publicStatusEnabled === true);
    if (initialSettings.defaultLibraryIds) setters.setDefaultLibraryIds(initialSettings.defaultLibraryIds);
    if (initialSettings.use24HourClock !== undefined) setters.setUse24HourClock(!!initialSettings.use24HourClock);
    if (initialSettings.showPosterQualityBadges !== undefined) setters.setShowPosterQualityBadges(initialSettings.showPosterQualityBadges !== false);
    if (initialSettings.allowTemporaryAccess !== undefined) setters.setAllowTemporaryAccess(!!initialSettings.allowTemporaryAccess);
    if (initialSettings.autoBackupEnabled !== undefined) setters.setAutoBackupEnabled(!!initialSettings.autoBackupEnabled);
    if (initialSettings.autoBackupIntervalDays !== undefined) setters.setAutoBackupIntervalDays(Number(initialSettings.autoBackupIntervalDays) || 2);
    if (initialSettings.autoBackupRetentionCount !== undefined) setters.setAutoBackupRetentionCount(Number(initialSettings.autoBackupRetentionCount) || 10);
    setters.setScannerEnabled(!!initialSettings.scannerEnabled);
    setters.setScannerHomeWidgetEnabled(!!initialSettings.scannerHomeWidgetEnabled);
    setters.setScannerWebhooksVisible(initialSettings.scannerWebhooksVisible !== false);
    setters.setScannerManualPathVisible(initialSettings.scannerManualPathVisible !== false);
    setters.setScanner(initialSettings.scanner || {
        minimumAge: '1m',
        verifyPathExists: false,
        authUsername: '',
        authPassword: '',
        triggers: { sonarr: [], radarr: [], lidarr: [] },
        targets: { plex: [], jellyfin: [], emby: [] },
    });
    setters.setUpgraderEnabled(!!initialSettings.upgraderEnabled);
    setters.setUpgraderAutomationEnabled(!!initialSettings.upgraderAutomationEnabled);
    setters.setUpgraderHuntMissingEpisodes(initialSettings.upgraderHuntMissingEpisodes !== false);
    setters.setUpgraderHuntAvailableMovies(initialSettings.upgraderHuntAvailableMovies !== false);
    setters.setUpgraderMinSizeGB(Math.max(0, Number(initialSettings.upgraderMinSizeGB) || 5));
    setters.setUpgraderMaxActionsPerHour(Math.max(1, Number(initialSettings.upgraderMaxActionsPerHour) || 25));
    setters.setUpgraderMinScoreDelta(Math.max(0, Number(initialSettings.upgraderMinScoreDelta ?? 10) || 0));
    setters.setUpgraderPreferences({
        preferDolbyVisionHdr: initialSettings.upgraderPreferences?.preferDolbyVisionHdr !== false,
        preferAtmos: initialSettings.upgraderPreferences?.preferAtmos !== false,
        preferRemux: initialSettings.upgraderPreferences?.preferRemux !== false,
        preferSeasonPacks: initialSettings.upgraderPreferences?.preferSeasonPacks !== false,
    });
    setters.setQcCleanupAutomationEnabled(!!initialSettings.qcCleanupAutomationEnabled);
    setters.setQcMetaDlMinutes(Math.max(1, Number(initialSettings.qcMetaDlMinutes) || 30));
    setters.setQcStalledHours(Math.max(1, Number(initialSettings.qcStalledHours) || 6));
    setters.setQcCompletedNotImportingMinutes(Math.max(1, Number(initialSettings.qcCompletedNotImportingMinutes) || 60));
    setters.setQcResearchThrottleHours(Math.max(1, Number(initialSettings.qcResearchThrottleHours) || 24));
    setters.setQcSnoozeDefaultHours(Math.max(1, Number(initialSettings.qcSnoozeDefaultHours) || 24));
    setters.setQcDiscordDigestEnabled(!!initialSettings.qcDiscordDigestEnabled);
    setters.setQcPreferImportDiscordOnly(initialSettings.qcPreferImportDiscordOnly !== false);
    setters.setQcQbitUrl(String(initialSettings.qcQbitUrl || ''));
    setters.setQcQbitUsername(String(initialSettings.qcQbitUsername || ''));
    setters.setQcQbitPassword(String(initialSettings.qcQbitPassword || ''));
    setters.setQcSabUrl(String(initialSettings.qcSabUrl || ''));
    setters.setQcSabApiKey(String(initialSettings.qcSabApiKey || ''));
    setters.setQcBlockedExtensions(
        Array.isArray(initialSettings.qcBlockedExtensions)
            ? initialSettings.qcBlockedExtensions.map((entry: string) => String(entry || '').trim()).filter(Boolean)
            : [],
    );
    const layout = normalizeSectionLayout(initialSettings.dashboardLayout);
    setters.dashboardLayoutRef.current = layout;
    setters.setDashboardLayout(layout);
    setters.setTestRecipient('');
    setters.setServers([]);
};
