import type { SettingsTabPanelProps } from './SettingsTabPanel';

type SettingsTabPanelPropsInput = {
    activeTab: SettingsTabPanelProps['activeTab'];
    addToast: SettingsTabPanelProps['addToast'];
    streamRulesSaveHandlerRef: SettingsTabPanelProps['streamRulesSaveHandlerRef'];
    [key: string]: any;
};

export const buildSettingsTabPanelProps = ({
    activeTab,
    addToast,
    streamRulesSaveHandlerRef,
    initialSettings,
    mediaServerType,
    token,
    plexServerUrl,
    jellyfinUrl,
    jellyfinApiKey,
    servers,
    selectedServer,
    checkInterval,
    libraries,
    defaultLibraryIds,
    hideStreamUsers,
    contactUrl,
    setMediaServerType,
    setToken,
    setPlexServerUrl,
    setJellyfinUrl,
    setJellyfinApiKey,
    setSelectedServer,
    setCheckInterval,
    setDefaultLibraryIds,
    setHideStreamUsers,
    setContactUrl,
    handleFetchServers,
    smtpHost,
    smtpPort,
    smtpUser,
    smtpPass,
    smtpFrom,
    smtpSecure,
    emailDaysBefore,
    testRecipient,
    isTestingSmtp,
    setSmtpHost,
    setSmtpPort,
    setSmtpUser,
    setSmtpPass,
    setSmtpFrom,
    setSmtpSecure,
    setEmailDaysBefore,
    setTestRecipient,
    handleTestEmail,
    newsletterFrequency,
    newsletterDay,
    publicDomain,
    isTestingNewsletter,
    isSendingNewsletter,
    setNewsletterFrequency,
    setNewsletterDay,
    setPublicDomain,
    handleTestNewsletter,
    handleSendNewsletterNow,
    inactiveCleanupEnabled,
    inactiveCleanupDays,
    setInactiveCleanupEnabled,
    setInactiveCleanupDays,
    arrInstances,
    tmdbApiKey,
    tvdbApiKey,
    tvdbPin,
    cacheRefreshMinutes,
    tautulliUrl,
    tautulliApiKey,
    jellystatUrl,
    jellystatApiKey,
    requestAppType,
    requestAppUrl,
    requestAppApiKey,
    ombiUrl,
    ombiApiKey,
    setArrInstances,
    setTmdbApiKey,
    setTvdbApiKey,
    setTvdbPin,
    setCacheRefreshMinutes,
    setTautulliUrl,
    setTautulliApiKey,
    setJellystatUrl,
    setJellystatApiKey,
    setRequestAppType,
    setRequestAppUrl,
    setRequestAppApiKey,
    setOmbiUrl,
    setOmbiApiKey,
    dashboardLayout,
    updateDashboardLayout,
    navOrder,
    setNavOrder,
    users,
    statusConfig,
    publicStatusEnabled,
    setPublicStatusEnabled,
    setStatusDraft,
    fetchStatusConfig,
    contactWhatsApp,
    contactEmail,
    setContactWhatsApp,
    setContactEmail,
    customLogoUrl,
    brandingTheme,
    backgroundImageUrl,
    useScrollRevealAnimations,
    useCinematicLoading,
    useBrandedSkeleton,
    useTrendingSlideshow,
    trendingSlideshowInterval,
    useTrendingSlideshowOnLogin,
    showLoginServerStats,
    use24HourClock,
    showPosterQualityBadges,
    allowTemporaryAccess,
    announcement,
    isPushingAnnouncement,
    referralEnabled,
    referralTrialDays,
    referralRewardDays,
    setCustomLogoUrl,
    setLogoFile,
    setBrandingTheme,
    setBackgroundImageUrl,
    setUseScrollRevealAnimations,
    setUseCinematicLoading,
    setUseBrandedSkeleton,
    setUseTrendingSlideshow,
    setTrendingSlideshowInterval,
    setUseTrendingSlideshowOnLogin,
    setShowLoginServerStats,
    setUse24HourClock,
    setShowPosterQualityBadges,
    setAllowTemporaryAccess,
    setAnnouncement,
    handlePushAnnouncement,
    setReferralEnabled,
    setReferralTrialDays,
    setReferralRewardDays,
    tasks,
    handleRunTask,
    systemHealth,
    highlightMaintenanceToggle,
    maintenanceExperimentalEnabled,
    autoBackupEnabled,
    autoBackupIntervalDays,
    autoBackupRetentionCount,
    backupRestoreText,
    backupFiles,
    isRestoringBackup,
    diagnostics,
    isLoadingDiagnostics,
    pagedAuditEntries,
    auditLogPage,
    totalAuditLogPages,
    isLoadingAuditLog,
    setMaintenanceExperimentalEnabled,
    setAutoBackupEnabled,
    setAutoBackupIntervalDays,
    setAutoBackupRetentionCount,
    setBackupRestoreText,
    handleDownloadBackup,
    handleCreateBackupFile,
    handleRestoreBackup,
    handleRestoreFromFile,
    fetchDiagnostics,
    fetchAuditLog,
    setAuditLogPage,
    deletedUsersLog,
    pagedEmailEntries,
    emailLogPage,
    totalEmailLogPages,
    handleUnblockDeletedUser,
    setEmailLogPage,
}: SettingsTabPanelPropsInput): SettingsTabPanelProps => ({
    activeTab,
    addToast,
    streamRulesSaveHandlerRef,
    mediaServer: {
        initialSettings,
        mediaServerType,
        token,
        plexServerUrl,
        jellyfinUrl,
        jellyfinApiKey,
        servers,
        selectedServer,
        onMediaServerTypeChange: setMediaServerType,
        onTokenChange: setToken,
        onPlexServerUrlChange: setPlexServerUrl,
        onJellyfinUrlChange: setJellyfinUrl,
        onJellyfinApiKeyChange: setJellyfinApiKey,
        onSelectedServerChange: setSelectedServer,
        onFetchServers: handleFetchServers,
        addToast,
    },
    smtp: {
        smtpHost,
        smtpPort,
        smtpUser,
        smtpPass,
        smtpFrom,
        smtpSecure,
        emailDaysBefore,
        testRecipient,
        isTestingSmtp,
        onSmtpHostChange: setSmtpHost,
        onSmtpPortChange: setSmtpPort,
        onSmtpUserChange: setSmtpUser,
        onSmtpPassChange: setSmtpPass,
        onSmtpFromChange: setSmtpFrom,
        onSmtpSecureChange: setSmtpSecure,
        onEmailDaysBeforeChange: setEmailDaysBefore,
        onTestRecipientChange: setTestRecipient,
        onTestEmail: handleTestEmail,
    },
    newsletter: {
        newsletterFrequency,
        newsletterDay,
        publicDomain,
        isTestingNewsletter,
        isSendingNewsletter,
        onNewsletterFrequencyChange: setNewsletterFrequency,
        onNewsletterDayChange: setNewsletterDay,
        onPublicDomainChange: setPublicDomain,
        onTestNewsletter: handleTestNewsletter,
        onSendNewsletterNow: handleSendNewsletterNow,
    },
    cleanup: {
        inactiveCleanupEnabled,
        inactiveCleanupDays,
        checkInterval,
        onInactiveCleanupEnabledChange: setInactiveCleanupEnabled,
        onInactiveCleanupDaysChange: setInactiveCleanupDays,
        onCheckIntervalChange: setCheckInterval,
    },
    mediaStack: {
        initialSettings,
        mediaServerType,
        arrInstances,
        tautulliUrl,
        tautulliApiKey,
        jellystatUrl,
        jellystatApiKey,
        requestAppType,
        requestAppUrl,
        requestAppApiKey,
        ombiUrl,
        ombiApiKey,
        onArrInstancesChange: setArrInstances,
        onTautulliUrlChange: setTautulliUrl,
        onTautulliApiKeyChange: setTautulliApiKey,
        onJellystatUrlChange: setJellystatUrl,
        onJellystatApiKeyChange: setJellystatApiKey,
        onRequestAppTypeChange: setRequestAppType,
        onRequestAppUrlChange: setRequestAppUrl,
        onRequestAppApiKeyChange: setRequestAppApiKey,
        onOmbiUrlChange: setOmbiUrl,
        onOmbiApiKeyChange: setOmbiApiKey,
        addToast,
    },
    metadata: {
        initialSettings,
        tmdbApiKey,
        tvdbApiKey,
        tvdbPin,
        cacheRefreshMinutes,
        onTmdbApiKeyChange: setTmdbApiKey,
        onTvdbApiKeyChange: setTvdbApiKey,
        onTvdbPinChange: setTvdbPin,
        onCacheRefreshMinutesChange: setCacheRefreshMinutes,
        addToast,
    },
    homeLayout: { layout: dashboardLayout, onChange: updateDashboardLayout },
    navigation: { navOrder, onNavOrderChange: setNavOrder },
    broadcast: { users },
    status: {
        statusConfig,
        publicStatusEnabled,
        onPublicStatusEnabledChange: setPublicStatusEnabled,
        onStatusDraftChange: setStatusDraft,
        fetchStatusConfig,
    },
    contact: {
        contactWhatsApp,
        contactEmail,
        contactUrl,
        announcement,
        isPushingAnnouncement,
        onContactWhatsAppChange: setContactWhatsApp,
        onContactEmailChange: setContactEmail,
        onContactUrlChange: setContactUrl,
        onAnnouncementChange: setAnnouncement,
        onPushAnnouncement: handlePushAnnouncement,
    },
    publicAccess: {
        allowTemporaryAccess,
        showLoginServerStats,
        useTrendingSlideshowOnLogin,
        referralEnabled,
        referralTrialDays,
        referralRewardDays,
        mediaServerType,
        libraries,
        defaultLibraryIds,
        hideStreamUsers,
        onAllowTemporaryAccessChange: setAllowTemporaryAccess,
        onShowLoginServerStatsChange: setShowLoginServerStats,
        onUseTrendingSlideshowOnLoginChange: setUseTrendingSlideshowOnLogin,
        onReferralEnabledChange: setReferralEnabled,
        onReferralTrialDaysChange: setReferralTrialDays,
        onReferralRewardDaysChange: setReferralRewardDays,
        onDefaultLibraryIdsChange: setDefaultLibraryIds,
        onHideStreamUsersChange: setHideStreamUsers,
    },
    branding: {
        mediaServerType,
        customLogoUrl,
        brandingTheme,
        backgroundImageUrl,
        useScrollRevealAnimations,
        useCinematicLoading,
        useBrandedSkeleton,
        useTrendingSlideshow,
        trendingSlideshowInterval,
        use24HourClock,
        showPosterQualityBadges,
        onCustomLogoUrlChange: setCustomLogoUrl,
        onLogoFileChange: setLogoFile,
        onBrandingThemeChange: setBrandingTheme,
        onBackgroundImageUrlChange: setBackgroundImageUrl,
        onUseScrollRevealAnimationsChange: setUseScrollRevealAnimations,
        onUseCinematicLoadingChange: setUseCinematicLoading,
        onUseBrandedSkeletonChange: setUseBrandedSkeleton,
        onUseTrendingSlideshowChange: setUseTrendingSlideshow,
        onTrendingSlideshowIntervalChange: setTrendingSlideshowInterval,
        onUse24HourClockChange: setUse24HourClock,
        onShowPosterQualityBadgesChange: setShowPosterQualityBadges,
        addToast,
    },
    invites: { addToast },
    tasks: { tasks, onRunTask: handleRunTask },
    system: {
        systemHealth,
        highlightMaintenanceToggle,
        maintenanceExperimentalEnabled,
        autoBackupEnabled,
        autoBackupIntervalDays,
        autoBackupRetentionCount,
        backupRestoreText,
        backupFiles,
        isRestoringBackup,
        diagnostics,
        mediaServerType,
        isLoadingDiagnostics,
        onMaintenanceExperimentalEnabledChange: setMaintenanceExperimentalEnabled,
        onAutoBackupEnabledChange: setAutoBackupEnabled,
        onAutoBackupIntervalDaysChange: setAutoBackupIntervalDays,
        onAutoBackupRetentionCountChange: setAutoBackupRetentionCount,
        onBackupRestoreTextChange: setBackupRestoreText,
        onDownloadBackup: handleDownloadBackup,
        onCreateBackupFile: handleCreateBackupFile,
        onRestoreBackup: handleRestoreBackup,
        onRestoreFromFile: handleRestoreFromFile,
        onRefreshDiagnostics: fetchDiagnostics,
    },
    logs: {
        deletedUsersLog,
        pagedAuditEntries,
        pagedEmailEntries,
        auditLogPage,
        totalAuditLogPages,
        emailLogPage,
        totalEmailLogPages,
        isLoadingAuditLog,
        onRefreshAuditLog: fetchAuditLog,
        onUnblockDeletedUser: handleUnblockDeletedUser,
        onEmailLogPageChange: setEmailLogPage,
        onAuditLogPageChange: setAuditLogPage,
    },
});
