import type React from 'react';

import { normalizeSectionLayout, type DashboardLayoutConfig } from '../shared/dashboardLayout';
import { ensureMaintenanceNavOrder } from './settingsNavOrder';

type SettingsHydrationSetters = {
    setToken: (value: string) => void;
    setMediaServerType: (value: 'plex' | 'jellyfin') => void;
    setPlexServerUrl: (value: string) => void;
    setJellyfinUrl: (value: string) => void;
    setJellyfinApiKey: (value: string) => void;
    setSelectedServer: (value: string) => void;
    setCheckInterval: (value: number) => void;
    setSmtpHost: (value: string) => void;
    setSmtpPort: (value: number) => void;
    setSmtpUser: (value: string) => void;
    setSmtpPass: (value: string) => void;
    setSmtpFrom: (value: string) => void;
    setSmtpSecure: (value: boolean) => void;
    setEmailDaysBefore: (value: number) => void;
    setNewsletterFrequency: (value: string) => void;
    setNewsletterDay: (value: number) => void;
    setInactiveCleanupEnabled: (value: boolean) => void;
    setInactiveCleanupDays: (value: number) => void;
    setPublicDomain: (value: string) => void;
    setRequestUrl: (value: string) => void;
    setContactUrl: (value: string) => void;
    setContactWhatsApp: (value: string) => void;
    setContactEmail: (value: string) => void;
    setSonarrUrl: (value: string) => void;
    setSonarrApiKey: (value: string) => void;
    setRadarrUrl: (value: string) => void;
    setRadarrApiKey: (value: string) => void;
    setTautulliUrl: (value: string) => void;
    setTautulliApiKey: (value: string) => void;
    setJellystatUrl: (value: string) => void;
    setJellystatApiKey: (value: string) => void;
    setRequestAppType: (value: string) => void;
    setRequestAppUrl: (value: string) => void;
    setRequestAppApiKey: (value: string) => void;
    setBrandingTheme: (value: string) => void;
    setCustomLogoUrl: (value: string) => void;
    setBackgroundImageUrl: (value: string) => void;
    setUseScrollRevealAnimations: (value: boolean) => void;
    setUseCinematicLoading: (value: boolean) => void;
    setUseBrandedSkeleton: (value: boolean) => void;
    setUseTrendingSlideshow: (value: boolean) => void;
    setTrendingSlideshowInterval: (value: number) => void;
    setTmdbApiKey: (value: string) => void;
    setReferralEnabled: (value: boolean) => void;
    setReferralTrialDays: (value: number) => void;
    setReferralRewardDays: (value: number) => void;
    setAnnouncement: (value: string) => void;
    setNavOrder: (value: string[]) => void;
    setHideStreamUsers: (value: string) => void;
    setUseTrendingSlideshowOnLogin: (value: boolean) => void;
    setPublicStatusEnabled: (value: boolean) => void;
    setDefaultLibraryIds: (value: string[]) => void;
    setUse24HourClock: (value: boolean) => void;
    setShowPosterQualityBadges: (value: boolean) => void;
    setAllowTemporaryAccess: (value: boolean) => void;
    setAutoBackupEnabled: (value: boolean) => void;
    setAutoBackupIntervalDays: (value: number) => void;
    setAutoBackupRetentionCount: (value: number) => void;
    setMaintenanceExperimentalEnabled: (value: boolean) => void;
    setDashboardLayout: (value: DashboardLayoutConfig) => void;
    setTestRecipient: (value: string) => void;
    setServers: (value: any[]) => void;
    dashboardLayoutRef: React.MutableRefObject<DashboardLayoutConfig>;
};

export const hydrateSettingsFromConfig = (initialSettings: any, setters: SettingsHydrationSetters) => {
    setters.setToken(initialSettings.token || '');
    setters.setMediaServerType(initialSettings.mediaServerType === 'jellyfin' ? 'jellyfin' : 'plex');
    setters.setPlexServerUrl(initialSettings.plexServerUrl || '');
    setters.setJellyfinUrl(initialSettings.jellyfinUrl || '');
    setters.setJellyfinApiKey(initialSettings.jellyfinApiKey || '');
    setters.setSelectedServer(initialSettings.serverIdentifier || '');
    setters.setCheckInterval(initialSettings.checkIntervalMinutes || 60);
    setters.setSmtpHost(initialSettings.smtpHost || '');
    setters.setSmtpPort(initialSettings.smtpPort || 587);
    setters.setSmtpUser(initialSettings.smtpUser || '');
    setters.setSmtpPass(initialSettings.smtpPass || '');
    setters.setSmtpFrom(initialSettings.smtpFrom || '');
    setters.setSmtpSecure(!!initialSettings.smtpSecure);
    setters.setEmailDaysBefore(initialSettings.emailDaysBefore || 7);
    setters.setNewsletterFrequency(initialSettings.newsletterFrequency || 'disabled');
    setters.setNewsletterDay(initialSettings.newsletterDay || 0);
    setters.setInactiveCleanupEnabled(!!initialSettings.inactiveCleanupEnabled);
    setters.setInactiveCleanupDays(initialSettings.inactiveCleanupDays || 90);
    setters.setPublicDomain(initialSettings.publicDomain || 'https://portal.yourdomain.com');
    setters.setRequestUrl(initialSettings.requestUrl || 'https://yourdomain.com');
    setters.setContactUrl(initialSettings.contactUrl || '');
    setters.setContactWhatsApp(initialSettings.contactWhatsApp || '');
    setters.setContactEmail(initialSettings.contactEmail || '');
    setters.setSonarrUrl(initialSettings.sonarrUrl || '');
    setters.setSonarrApiKey(initialSettings.sonarrApiKey || '');
    setters.setRadarrUrl(initialSettings.radarrUrl || '');
    setters.setRadarrApiKey(initialSettings.radarrApiKey || '');
    setters.setTautulliUrl(initialSettings.tautulliUrl || '');
    setters.setTautulliApiKey(initialSettings.tautulliApiKey || '');
    setters.setJellystatUrl(initialSettings.jellystatUrl || '');
    setters.setJellystatApiKey(initialSettings.jellystatApiKey || '');
    setters.setRequestAppType(initialSettings.requestAppType === 'overseerr' ? 'seerr' : (initialSettings.requestAppType || 'none'));
    setters.setRequestAppUrl(initialSettings.requestAppUrl || '');
    setters.setRequestAppApiKey(initialSettings.requestAppApiKey || '');
    setters.setBrandingTheme(localStorage.getItem('portal-theme') || initialSettings.brandingTheme || 'plex');
    setters.setCustomLogoUrl(initialSettings.customLogoUrl || '');
    setters.setBackgroundImageUrl(initialSettings.backgroundImageUrl || '');
    setters.setUseScrollRevealAnimations(!!initialSettings.useScrollRevealAnimations);
    setters.setUseCinematicLoading(!!initialSettings.useCinematicLoading);
    setters.setUseBrandedSkeleton(initialSettings.useBrandedSkeleton !== false);
    setters.setUseTrendingSlideshow(!!initialSettings.useTrendingSlideshow);
    setters.setTrendingSlideshowInterval(initialSettings.trendingSlideshowInterval || 30);
    setters.setTmdbApiKey(initialSettings.tmdbApiKey || '');
    setters.setReferralEnabled(!!initialSettings.referralEnabled);
    setters.setReferralTrialDays(initialSettings.referralTrialDays || 3);
    setters.setReferralRewardDays(initialSettings.referralRewardDays || 7);
    setters.setAnnouncement(initialSettings.announcement || '');
    if (initialSettings.navOrder) setters.setNavOrder(ensureMaintenanceNavOrder(initialSettings.navOrder));
    setters.setHideStreamUsers(initialSettings.hideStreamUsers === 'hidden' ? 'hidden' : 'anonymous');
    setters.setUseTrendingSlideshowOnLogin(initialSettings.useTrendingSlideshowOnLogin !== false);
    setters.setPublicStatusEnabled(initialSettings.publicStatusEnabled !== false);
    if (initialSettings.defaultLibraryIds) setters.setDefaultLibraryIds(initialSettings.defaultLibraryIds);
    if (initialSettings.use24HourClock !== undefined) setters.setUse24HourClock(!!initialSettings.use24HourClock);
    if (initialSettings.showPosterQualityBadges !== undefined) setters.setShowPosterQualityBadges(initialSettings.showPosterQualityBadges !== false);
    if (initialSettings.allowTemporaryAccess !== undefined) setters.setAllowTemporaryAccess(!!initialSettings.allowTemporaryAccess);
    if (initialSettings.autoBackupEnabled !== undefined) setters.setAutoBackupEnabled(!!initialSettings.autoBackupEnabled);
    if (initialSettings.autoBackupIntervalDays !== undefined) setters.setAutoBackupIntervalDays(Number(initialSettings.autoBackupIntervalDays) || 2);
    if (initialSettings.autoBackupRetentionCount !== undefined) setters.setAutoBackupRetentionCount(Number(initialSettings.autoBackupRetentionCount) || 10);
    if (initialSettings.maintenanceExperimentalEnabled !== undefined) setters.setMaintenanceExperimentalEnabled(!!initialSettings.maintenanceExperimentalEnabled);
    const layout = normalizeSectionLayout(initialSettings.dashboardLayout);
    setters.dashboardLayoutRef.current = layout;
    setters.setDashboardLayout(layout);
    setters.setTestRecipient('');
    setters.setServers([]);
};
