import type { DashboardLayoutConfig } from '../shared/dashboardLayout';
import type { ArrInstance, PlexServer } from '../shared/types';

export type SettingsFormValues = {
    token: string;
    mediaServerType: 'plex' | 'jellyfin';
    plexServerUrl: string;
    jellyfinUrl: string;
    jellyfinApiKey: string;
    servers: PlexServer[];
    selectedServer: string;
    checkInterval: number;
    hideStreamUsers: string;
    useTrendingSlideshowOnLogin: boolean;
    showLoginServerStats: boolean;
    publicStatusEnabled: boolean;
    defaultLibraryIds: string[];
    smtpHost: string;
    smtpPort: number;
    smtpUser: string;
    smtpPass: string;
    smtpFrom: string;
    smtpSecure: boolean;
    emailDaysBefore: number;
    testRecipient: string;
    newsletterFrequency: string;
    newsletterDay: number;
    publicDomain: string;
    contactUrl: string;
    contactWhatsApp: string;
    contactEmail: string;
    discordEnabled: boolean;
    discordInviteUrl: string;
    discordChatChannelLabel: string;
    discordMediaChannelLabel: string;
    discordGuildId: string;
    discordBotToken: string;
    discordBotEnabled: boolean;
    discordWebhookUrl: string;
    discordNotifyRequestUpdates: boolean;
    discordNotifyIssueReplies: boolean;
    discordNotifyWatchlistAvailable: boolean;
    inactiveCleanupEnabled: boolean;
    inactiveCleanupDays: number;
    arrInstances: ArrInstance[];
    tautulliUrl: string;
    tautulliApiKey: string;
    jellystatUrl: string;
    jellystatApiKey: string;
    requestAppType: string;
    requestAppUrl: string;
    requestAppApiKey: string;
    requestAppMembershipSync: boolean;
    ombiUrl: string;
    ombiApiKey: string;
    dashboardLayout: DashboardLayoutConfig;
    customLogoUrl: string;
    backgroundImageUrl: string;
    useScrollRevealAnimations: boolean;
    useCinematicLoading: boolean;
    useBrandedSkeleton: boolean;
    useTrendingSlideshow: boolean;
    trendingSlideshowInterval: number;
    tmdbApiKey: string;
    tvdbApiKey: string;
    tvdbPin: string;
    cacheRefreshMinutes: number;
    brandingTheme: string;
    referralEnabled: boolean;
    referralTrialDays: number;
    referralRewardDays: number;
    announcement: string;
    use24HourClock: boolean;
    showPosterQualityBadges: boolean;
    allowTemporaryAccess: boolean;
    navOrder: string[];
    logoFile: File | null;
};

export type SaveAdminValues = {
    customLogoUrl: string;
    autoBackupEnabled: boolean;
    autoBackupIntervalDays: number;
    autoBackupRetentionCount: number;
};
