import { useCallback, useRef, useState } from 'react';

import { DEFAULT_DASHBOARD_LAYOUT, type DashboardLayoutConfig } from '../shared/dashboardLayout';
import { createInitialSettingsFormValues } from './settingsFormInitialValues';
import type { SaveAdminValues, SettingsFormValues } from './settingsFormTypes';
import { buildSettingsSavePayload } from './settingsSavePayload';

export type { SaveAdminValues, SettingsFormValues } from './settingsFormTypes';

export const useSettingsFormState = () => {
    const [values, setValues] = useState<SettingsFormValues>(createInitialSettingsFormValues);
    const dashboardLayoutRef = useRef<DashboardLayoutConfig>(DEFAULT_DASHBOARD_LAYOUT);

    const setField = useCallback(<K extends keyof SettingsFormValues>(key: K, value: SettingsFormValues[K]) => {
        setValues(current => ({ ...current, [key]: value }));
    }, []);

    const updateDashboardLayout = useCallback((next: DashboardLayoutConfig) => {
        dashboardLayoutRef.current = next;
        setField('dashboardLayout', next);
    }, [setField]);

    const createSavePayload = useCallback((adminValues: SaveAdminValues) => buildSettingsSavePayload({
        token: values.token,
        mediaServerType: values.mediaServerType,
        selectedServer: values.selectedServer,
        plexServerUrl: values.plexServerUrl,
        jellyfinUrl: values.jellyfinUrl,
        jellyfinApiKey: values.jellyfinApiKey,
        checkInterval: values.checkInterval,
        smtpHost: values.smtpHost,
        smtpPort: values.smtpPort,
        smtpUser: values.smtpUser,
        smtpPass: values.smtpPass,
        smtpFrom: values.smtpFrom,
        smtpSecure: values.smtpSecure,
        emailDaysBefore: values.emailDaysBefore,
        newsletterFrequency: values.newsletterFrequency,
        newsletterDay: values.newsletterDay,
        inactiveCleanupEnabled: values.inactiveCleanupEnabled,
        inactiveCleanupDays: values.inactiveCleanupDays,
        publicDomain: values.publicDomain,
        contactUrl: values.contactUrl,
        contactEmail: values.contactEmail,
        discordEnabled: values.discordEnabled,
        discordInviteUrl: values.discordInviteUrl,
        discordChatChannelLabel: values.discordChatChannelLabel,
        discordMediaChannelLabel: values.discordMediaChannelLabel,
        discordGuildId: values.discordGuildId,
        discordBotToken: values.discordBotToken,
        discordBotEnabled: values.discordBotEnabled,
        discordWebhookUrl: values.discordWebhookUrl,
        discordNotifyRequestUpdates: values.discordNotifyRequestUpdates,
        discordNotifyIssueReplies: values.discordNotifyIssueReplies,
        discordNotifyWatchlistAvailable: values.discordNotifyWatchlistAvailable,
        discordLlmEnabled: values.discordLlmEnabled,
        discordLlmUrl: values.discordLlmUrl,
        discordLlmApiKey: values.discordLlmApiKey,
        discordLlmModel: values.discordLlmModel,
        discordAgentEnabled: values.discordAgentEnabled,
        discordSearxngUrl: values.discordSearxngUrl,
        discordBraveSearchApiKey: values.discordBraveSearchApiKey,
        discordTavilyApiKey: values.discordTavilyApiKey,
        discordMentionNl: values.discordMentionNl,
        arrInstances: values.arrInstances,
        tautulliUrl: values.tautulliUrl,
        tautulliApiKey: values.tautulliApiKey,
        jellystatUrl: values.jellystatUrl,
        jellystatApiKey: values.jellystatApiKey,
        customLogoUrl: adminValues.customLogoUrl,
        brandingTheme: values.brandingTheme,
        backgroundImageUrl: values.backgroundImageUrl,
        useScrollRevealAnimations: values.useScrollRevealAnimations,
        useCinematicLoading: values.useCinematicLoading,
        useBrandedSkeleton: values.useBrandedSkeleton,
        useTrendingSlideshow: values.useTrendingSlideshow,
        trendingSlideshowInterval: values.trendingSlideshowInterval,
        tmdbApiKey: values.tmdbApiKey,
        tvdbApiKey: values.tvdbApiKey,
        tvdbPin: values.tvdbPin,
        cacheRefreshMinutes: values.cacheRefreshMinutes,
        referralEnabled: values.referralEnabled,
        referralTrialDays: values.referralTrialDays,
        referralRewardDays: values.referralRewardDays,
        announcement: values.announcement,
        navOrder: values.navOrder,
        navHiddenKeys: values.navHiddenKeys,
        hideStreamUsers: values.hideStreamUsers,
        useTrendingSlideshowOnLogin: values.useTrendingSlideshowOnLogin,
        showLoginServerStats: values.showLoginServerStats,
        publicStatusEnabled: values.publicStatusEnabled,
        defaultLibraryIds: values.defaultLibraryIds,
        use24HourClock: values.use24HourClock,
        showPosterQualityBadges: values.showPosterQualityBadges,
        autoBackupEnabled: adminValues.autoBackupEnabled,
        autoBackupIntervalDays: adminValues.autoBackupIntervalDays,
        autoBackupRetentionCount: adminValues.autoBackupRetentionCount,
        upgraderEnabled: values.upgraderEnabled,
        upgraderAutomationEnabled: values.upgraderAutomationEnabled,
        upgraderHuntMissingEpisodes: values.upgraderHuntMissingEpisodes,
        upgraderHuntAvailableMovies: values.upgraderHuntAvailableMovies,
        upgraderMinSizeGB: values.upgraderMinSizeGB,
        upgraderMaxActionsPerHour: values.upgraderMaxActionsPerHour,
        upgraderMaxDownloadsPerLibrary: values.upgraderMaxDownloadsPerLibrary,
        upgraderMinScoreDelta: values.upgraderMinScoreDelta,
        upgraderHuntIntensity: values.upgraderHuntIntensity,
        upgraderPreferences: values.upgraderPreferences,
        qcCleanupAutomationEnabled: values.qcCleanupAutomationEnabled,
        qcCleanupAggression: values.qcCleanupAggression,
        qcIntegrityEnabled: values.qcIntegrityEnabled,
        qcIntegrityAutomationEnabled: values.qcIntegrityAutomationEnabled,
        qcIntegrityRequireAudio: values.qcIntegrityRequireAudio,
        qcIntegrityIncludeMusic: values.qcIntegrityIncludeMusic,
        qcIntegrityXxhashEnabled: values.qcIntegrityXxhashEnabled,
        qcIntegrityPathMaps: values.qcIntegrityPathMaps,
        qcIntegrityMaxPerCycle: values.qcIntegrityMaxPerCycle,
        qcIntegrityConcurrency: values.qcIntegrityConcurrency,
        qcIntegrityPlayabilityConcurrency: values.qcIntegrityPlayabilityConcurrency,
        qcIntegrityBreakerMaxFindings: values.qcIntegrityBreakerMaxFindings,
        qcIntegrityBreakerMaxPercent: values.qcIntegrityBreakerMaxPercent,
        qcIntegrityPauseWhenSessions: values.qcIntegrityPauseWhenSessions,
        qcIntegrityNightlyHour: values.qcIntegrityNightlyHour,
        qcIntegrityDiscordDigestEnabled: values.qcIntegrityDiscordDigestEnabled,
        qcIntegrityDecodeWindowSec: values.qcIntegrityDecodeWindowSec,
        qcIntegrityDecodeTimeoutMs: values.qcIntegrityDecodeTimeoutMs,
        qcIntegrityWebhookUsername: values.qcIntegrityWebhookUsername,
        qcIntegrityWebhookPassword: values.qcIntegrityWebhookPassword,
        qcMetaDlMinutes: values.qcMetaDlMinutes,
        qcStalledHours: values.qcStalledHours,
        qcSlowDownloadFloorKbps: values.qcSlowDownloadFloorKbps,
        qcSlowDownloadMinAgeHours: values.qcSlowDownloadMinAgeHours,
        qcCompletedNotImportingMinutes: values.qcCompletedNotImportingMinutes,
        qcOrphanGraceMinutes: values.qcOrphanGraceMinutes,
        qcMaxStrikes: values.qcMaxStrikes,
        qcResearchThrottleHours: values.qcResearchThrottleHours,
        qcSnoozeDefaultHours: values.qcSnoozeDefaultHours,
        qcDiscordDigestEnabled: values.qcDiscordDigestEnabled,
        qcQbitUrl: values.qcQbitUrl,
        qcQbitUsername: values.qcQbitUsername,
        qcQbitPassword: values.qcQbitPassword,
        qcSabUrl: values.qcSabUrl,
        qcSabApiKey: values.qcSabApiKey,
        qcBlockedExtensions: values.qcBlockedExtensions,
        dashboardLayout: dashboardLayoutRef.current,
    }), [values]);

    return {
        values,
        setField,
        dashboardLayoutRef,
        updateDashboardLayout,
        createSavePayload,
    };
};

export type SettingsFormState = ReturnType<typeof useSettingsFormState>;
